- server/src/main/java/com/CreatorConnect/server/auth/handler/OAuth2MemberSuccessHandler.java
- server/src/main/java/com/CreatorConnect/server/auth/oauth/google/GoogleOauthController.java
- server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
> [be] fix: oauth google login 수정

- server/src/main/java/com/CreatorConnect/server/feedbackboard/dto/FeedbackBoardResponseDto.java
- server/src/main/java/com/CreatorConnect/server/feedbackboard/entity/FeedbackBoard.java
- server/src/main/java/com/CreatorConnect/server/freeboard/dto/FreeBoardDto.java
- server/src/main/java/com/CreatorConnect/server/freeboard/entity/FreeBoard.java
자유게시판, 피드백게시판에서
멤버의 프로필 이미지URL을 리스폰스 바디에 추가했습니다
> [be] feat: profileImageUrl 추가

- server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
- server/src/main/java/com/CreatorConnect/server/category/controller/CategoryController.java
- server/src/main/java/com/CreatorConnect/server/category/dto/CategoryDto.java
- server/src/main/java/com/CreatorConnect/server/category/dto/CategoryResponseDto.java
- server/src/main/java/com/CreatorConnect/server/category/mapper/CategoryMapper.java
- server/src/main/java/com/CreatorConnect/server/category/service/CategoryService.java
- server/src/main/java/com/CreatorConnect/server/feedbackboard/repository/FeedbackBoardRepository.java
- server/src/main/java/com/CreatorConnect/server/feedbackcategory/controller/FeedbackCategoryController.java
- server/src/main/java/com/CreatorConnect/server/feedbackcategory/mapper/FeedbackCategoryMapper.java
- server/src/main/java/com/CreatorConnect/server/feedbackcategory/service/FeedbackCategoryService.java
- server/src/main/java/com/CreatorConnect/server/freeboard/service/FreeBoardService.java
[be] feat: category CRUD 기능 추가
[be] fix: 카테고리별 게시글 목록 조회기능(자유,피드백) 로그인없이 조회 가능하게 수정
[be] fix: 피드백카테고리 어드민만 생성,수정,삭제 가능하게 수정
> [be] feat: category CRUD 기능 추가

- server/src/main/java/com/CreatorConnect/server/auth/filter/HttpServletWrappingFilter.java
- server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
로그인시 - Authorization, RefreshToken, Content-Length 그 외 나머지 - Content-Length
> [be] feat: response header 에 Access-Control-Expose-Headers 추가

- server/src/main/java/com/CreatorConnect/server/feedbackboard/repository/FeedbackBoardRepository.java
- server/src/main/java/com/CreatorConnect/server/feedbackboard/service/FeedbackBoardService.java
1. 피드백 수정, 삭제시 멤버 아이디 확인절차 추가
2. 피드백 카테고리 목록 조회 결과와 pageInfo가 맞게 출력되도록 수정
3. 주석 추가
> [be] fix: feedbackboard

- server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
- server/src/main/java/com/CreatorConnect/server/feedbackboard/service/FeedbackBoardService.java
- server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
- server/src/main/java/com/CreatorConnect/server/freeboard/service/FreeBoardService.java
> [be] feat: 게시판 정렬 기능 추가 -최신순, 등록순, 인기순

- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberFollowResponseDto.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
- server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
> Be feat/member follow following

- server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
- server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
- server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
- server/src/main/java/com/CreatorConnect/server/member/bookmark/repository/BookmarkRepository.java
- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
> Be feat/bookmark

- server/src/main/java/com/CreatorConnect/server/advice/GlobalExceptionAdvice.java
- server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
- server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
- server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationFailureHandler.java
- server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
- server/src/main/java/com/CreatorConnect/server/board/feedbackboard/dto/FeedbackBoardResponseDto.java
- server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
- server/src/main/java/com/CreatorConnect/server/board/freeboard/conroller/FreeBoardController.java
- server/src/main/java/com/CreatorConnect/server/board/freeboard/dto/FreeBoardDto.java
- server/src/main/java/com/CreatorConnect/server/board/freeboard/entity/FreeBoard.java
- server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
- server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberBoardResponseDto.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberFollowResponseDto.java
- server/src/main/java/com/CreatorConnect/server/response/ErrorResponder.java
- server/src/main/java/com/CreatorConnect/server/response/ErrorResponse.java
- server/src/main/java/com/CreatorConnect/server/response/MultiResponseDto.java
- server/src/main/java/com/CreatorConnect/server/response/PageInfo.java
- server/src/main/java/com/CreatorConnect/server/response/SingleResponseDto.java
> be-feat/ member memberpage 수정

- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
- server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
- server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
- server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
> Be feat/member

- server/src/main/java/com/CreatorConnect/server/board/categories/jobcategory/controller/JobCategoryController.java
- server/src/main/java/com/CreatorConnect/server/board/jobboard/controller/JobBoardController.java
구인구직 게시판 / 구인구직 카테고리 - post, patch, delete 동작 시 토큰 검증 기능 추가
> [be] feat: 구인구직 게시판 / 구인구직 카테고리 - 토큰 검증 기능 추가

- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/controller/JobCommentController.java
- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/entity/JobComment.java
- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/mapper/JobCommentMapper.java
- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/repository/JobCommentRepository.java
- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/service/JobCommentServiceImpl.java
- server/src/main/java/com/CreatorConnect/server/board/jobboard/entity/JobBoard.java
- server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/controller/JobReCommentController.java
- server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/entity/JobReComment.java
- server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/mapper/JobReCommentMapper.java
- server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/repository/JobReCommentRepository.java
- server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/service/JobReCommentServiceImpl.java
- server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
> [be] feat: jobComment, JobReComment 기능 추가

- server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
- server/src/main/java/com/CreatorConnect/server/board/notice/controller/NoticeController.java
- server/src/main/java/com/CreatorConnect/server/board/notice/dto/NoticeDto.java
- server/src/main/java/com/CreatorConnect/server/board/notice/entity/Notice.java
- server/src/main/java/com/CreatorConnect/server/board/notice/mapper/NoticeMapper.java
- server/src/main/java/com/CreatorConnect/server/board/notice/repository/NoticeRepository.java
- server/src/main/java/com/CreatorConnect/server/board/notice/service/NoticeService.java
- server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
> [be] feat: 공지사항 기능 추가

- server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
> [oauth2 redirect path 수정]

- server/build.gradle
- server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
- server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/controller/YoutubeApiController.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/dto/YoutubeApiDto.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoEntity.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoPK.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/mapper/YoutubeApiMapper.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/repository/YoutubeApiRepository.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
1. 최초 조회시 데이터베이스에 저장 후 출력
2. 중복 조회시 api할당량 사용을 최소화하기 위해 데이터베이스에서 조회
3. 중복 조회시 만약 entity값이 수정된지 1일이상 지났다면  youtubeAPI 사용해서 entity 업데이트
> [be] feat: 인기 급상승 영상 목록 조회 기능 추가

- server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/controller/YoutubeApiController.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
1. 서비스 가능한 카테고리 id값을 받았는지 먼저 체크해서 불필요한 api 호출 차단
2. url 및 Exception 수정
> [be] fix: 유튜브 api

- server/build.gradle
- server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
- server/src/main/java/com/CreatorConnect/server/auth/filter/HttpServletWrappingFilter.java
- server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
- server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
- server/src/main/java/com/CreatorConnect/server/auth/oauth/service/OAuth2MemberService.java
- server/src/main/java/com/CreatorConnect/server/helper/email/EmailConfiguration.java
- server/src/main/java/com/CreatorConnect/server/helper/email/EmailSendable.java
- server/src/main/java/com/CreatorConnect/server/helper/email/EmailSender.java
- server/src/main/java/com/CreatorConnect/server/helper/email/MockEmailSendable.java
- server/src/main/java/com/CreatorConnect/server/helper/email/MockExceptionEmailSendable.java
- server/src/main/java/com/CreatorConnect/server/helper/email/SimpleEmailSendable.java
- server/src/main/java/com/CreatorConnect/server/helper/email/TemplateEmailSendable.java
- server/src/main/java/com/CreatorConnect/server/helper/event/MemberRegistrationApplicationEvent.java
- server/src/main/java/com/CreatorConnect/server/helper/event/MemberRegistrationEventListener.java
- server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
- server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
- server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
- server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
- server/src/main/resources/templates/email-registration-member.html
> be 회원가입시 이메일 인증 로직 추가

- server/src/main/java/com/CreatorConnect/server/board/categories/category/service/CategoryService.java
- server/src/main/java/com/CreatorConnect/server/board/categories/feedbackcategory/service/FeedbackCategoryService.java
- server/src/main/java/com/CreatorConnect/server/board/categories/jobcategory/service/JobCategoryService.java
> [be] fix :  카테고리 목록조회 등록순으로 수정

- server/src/main/java/com/CreatorConnect/server/youtubeapi/dto/YoutubeApiDto.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoEntity.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/mapper/YoutubeApiMapper.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
> [be] fix : youtubeId 추가

- client/src/app/feedback/edit/Form.tsx
- client/src/app/feedback/write/Form.tsx
- client/src/app/free/edit/Form.tsx
- client/src/app/free/write/Form.tsx
- client/src/app/job/edit/Form.tsx
- client/src/app/job/write/Form.tsx
- client/src/app/promotion/edit/Form.tsx
- client/src/app/promotion/write/Form.tsx
- client/src/components/Header/InputModal.tsx
- client/src/components/Header/SearchDiv.tsx
- client/src/components/KeywordCloud.tsx
- client/src/hooks/query/useFetchKeywords.ts
- client/src/hooks/useTags.ts
- client/src/types/api/keywords.ts
1. 검색창 에러 해결
2. 태그 생성 방법에 대한 설명 텍스트 추가
3. 게시글 작성 길이에 대한 내용 추가
> [fe] fix: 코드 정리 및 요구사항 반영

- server/src/main/java/com/CreatorConnect/server/board/comments/feedbackcomment/entity/FeedbackComment.java
- server/src/main/java/com/CreatorConnect/server/board/comments/freecomment/entity/FreeComment.java
- server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/entity/JobComment.java
- server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
- server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
1. 대댓글 존재해도 게시물 삭제가능하게 수정
2. 유튜브api 썸네일 제공크기 320  *  180 에서 640  *  480로 수정
3. 프로모션 엔티티 memberId -> promotionId로 수정
> [be] fix : 대댓글, 유튜브썸네일 

- server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
> [be] fix : 썸네일 크기 변경

- server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
- server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
- server/src/main/java/com/CreatorConnect/server/board/tag/service/PromotionBoardTagService.java
> [be] fix : 오류나는 부분 수정

- server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
> [be] refactor: promotionboard

- server/src/main/java/com/CreatorConnect/server/board/search/entity/PopularSearch.java
> [be] refactor: search

- server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
> [be] fix : 주석수정

- client/src/components/Header/NickModal.tsx
로그아웃 요청: post -> delete / 리프레시 토큰 추가
> [fe-fix] 로그아웃 재 구현

- server/src/main/java/com/CreatorConnect/server/board/freeboard/controller/FreeBoardController.java
- server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
> [be] fix : freeboard

- client/src/Layout/Header.tsx
- client/src/components/Header/AuthCheck.tsx
- client/src/components/Header/HeaderLogo.tsx
- client/src/components/Header/LoginSide.tsx
- client/src/components/Navbar/Rank/RankClose.tsx
- client/src/components/Navbar/Rank/RankModal.tsx
- client/src/hooks/useCurrentRank.tsx
- client/tailwind.config.js
[헤더-닉네임, 모달창 사이즈]
[AuthCeck]
[실검 작성 중]
[실검 10개]
[실검 close 단일 항목]
[헤더 로고 사이즈]
> 실검, 로고 사이즈,  AuthCheck 등

- client/src/apis/index.ts
- client/src/apis/ssr.ts
- client/src/app/profile/[memberId]/edit/ProfileEditForm.tsx
- client/src/components/Header/LoginSide.tsx
- client/src/components/Header/NickModal.tsx
1. 게시글 수정 시 <title> 즉시 반영 안 되는 문제 ( 일단 제대로 동작하도록 만듦 )
2. 회원 정보 수정 시 로그아웃 반영 및 데이터 수정 하지 않으면 전달하지 않는 코드 추가
> [fe] fix: 버그 수정
